version: "3.9"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/redis-python-devcontainer:cached
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["sleep", "infinity"]

  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/db

volumes:
  redis_data:
  redisinsight_data: